project_id = "sofrxfgjptargppbepbi"

[functions.linkedin-webhook]
verify_jwt = false

[functions.extract-cv-text]
verify_jwt = false

[functions.submit_application]
verify_jwt = false

[functions.redirect-webhook]
verify_jwt = false
