project_id = "sofrxfgjptargppbepbi"

[functions.linkedin-webhook]
verify_jwt = false

[functions.extract-cv-text]
verify_jwt = false

[functions.submit_application]
verify_jwt = false

[functions.redirect-webhook]
verify_jwt = false

[functions.update-formatted-cv]
verify_jwt = false

[functions.fetch-linkedin-account]
verify_jwt = false

[functions.disconnect-linkedin-account]
verify_jwt = false

[functions.linkedin-search]
verify_jwt = false

[functions.send-push-webhook]
verify_jwt = false
